### ISSUE TITLE
Language not changing after selecting local language

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/guides#10]
Customers website is showing english words even selecting French language.

![download (98)](https://user-images.githubusercontent.com/66590860/107947514-6f3a4280-6fcd-11eb-93b2-97ea3fabe783.png)
![download (99)](https://user-images.githubusercontent.com/66590860/107947518-6fd2d900-6fcd-11eb-816d-6cb8e428502b.png)

**Comment by jadecoyacot123** [comment]
Customers website is showing english words even selecting French language. 

https://larecupvs.ch/tout
![download (99)](https://user-images.githubusercontent.com/66590860/107947468-63e71700-6fcd-11eb-991a-c4f46bc47e37.png)
![download (98)](https://user-images.githubusercontent.com/66590860/107947473-65b0da80-6fcd-11eb-8392-ea727489997f.png)

**Comment by oliverservin** [comment]
Issue moved to Yclas repo https://github.com/yclas/yclas/issues/3153.
