### ISSUE TITLE
Location guides

### ISSUE THREAD

**Issue by neo22s** [yclas/guides#7]
Chema, \[26.11.20 08:33\]

https://guides.yclas.com/#/Classifieds-add-location here there's a link to a file that is not working

Chema, \[26.11.20 08:33\]

Here there's not link to that file https://guides.yclas.com/#/Classifieds-how-to-import-tool-for-categories-and-location

Chema, \[26.11.20 08:33\]

This guide I do not think it's needed https://guides.yclas.com/#/Classifieds-how-to-import-tool-for-categories-and-location

**Comment by neo22s** [comment]
@oliverds review sample file seems it's not working please.

**Comment by oliverservin** [comment]
The sample file on https://guides.yclas.com/#/Classifieds-add-location page should work now.

It was linked before to an outdated .csv file.

**Comment by neo22s** [comment]
thanks!! @jadecoyacot123 please check ;)

**Comment by neo22s** [comment]
@jadecoyacot123 finish the guides please.
