### ISSUE TITLE
Atlantic Theme not showing up the membership plans 

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/guides#9]
Trying to enable Membership subscription and when new user publishes, it doesnt show up the plan for Atlantic  Theme. 
So I tried another theme, like czsale and the plan showed up.
https://akosibadak.tk/publish-new.html
![download (5)](https://user-images.githubusercontent.com/66590860/105137210-ee9f3800-5b2d-11eb-9f23-09eec8ed2d01.png)
![download (4)](https://user-images.githubusercontent.com/66590860/105137216-f068fb80-5b2d-11eb-8b51-0a540d9ba864.png)

Screen Shots are attached .

**Comment by oliverservin** [comment]
Duplicated issue. https://github.com/yclas/yclas/issues/3136
